#encoding:utf-8 
#Given two strings s and t which consist of only lowercase letters.
#String t is generated by random shuffling string s and then add one more letter at a random position.
#Find the letter that was added in t.

class Solution:
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        s_arr = sorted(s)
        t_arr = sorted(t)
        n = 0
        s_arr.append(' ')
        while True:
        	if s_arr[n] == t_arr[n]:
        		n += 1
        	else:
        		return t_arr[n]
        		break